services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.sc2
    network_mode: "host"
    working_dir: /root
    volumes:
      - ./runner:/root/runner
      - ${SC2_MAPS_PATH}:/root/StarCraftII/Maps
      - ${REPLAYS_DIR}:/root/replays
    command: bash /root/runner/run_docker.sh
