# Generated by Django 6.0.1 on 2026-01-21 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_group_id', models.IntegerField()),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('map_name', models.CharField(max_length=100)),
                ('opponent_race', models.CharField(choices=[('Protoss', 'Protoss'), ('Terran', 'Terran'), ('Zerg', 'Zerg'), ('Random', 'Random')], max_length=7)),
                ('opponent_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('MediumHard', 'Mediumhard'), ('Hard', 'Hard'), ('Harder', 'Harder'), ('VeryHard', 'Veryhard'), ('CheatVision', 'Cheatvision'), ('CheatMoney', 'Cheatmoney'), ('CheatInsane', 'Cheatinsane')], max_length=11)),
                ('opponent_build', models.CharField(choices=[('Air', 'Air'), ('Macro', 'Macro'), ('Power', 'Power'), ('Rush', 'Rush'), ('Timing', 'Timing'), ('RandomBuild', 'Randombuild')], max_length=15)),
                ('result', models.CharField(choices=[('Victory', 'Victory'), ('Defeat', 'Defeat'), ('Tie', 'Tie'), ('Undecided', 'Undecided')], max_length=50)),
                ('replay_path', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_in_game_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_lab.match')),
            ],
            options={
                'db_table': 'match_event',
            },
        ),
    ]
