# Generated by Django 6.0.1 on 2026-01-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='type',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
