# Generated by Django 6.0.1 on 2026-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0002_matchevent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='matchevent',
            name='game_timestamp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
