# Generated by Django 6.0.1 on 2026-01-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0003_remove_matchevent_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='replay_path',
        ),
    ]
