# Generated by Django 6.0.1 on 2026-02-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0005_testgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='test_group_id',
        ),
        migrations.AddField(
            model_name='match',
            name='test_group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='test_lab.testgroup'),
            preserve_default=False,
        ),
    ]
