# Generated by Django 6.0.1 on 2026-03-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0006_remove_match_test_group_id_match_test_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('race', models.CharField(choices=[('Protoss', 'Protoss'), ('Terran', 'Terran'), ('Zerg', 'Zerg'), ('Random', 'Random')], max_length=7)),
                ('bot_file', models.CharField(help_text='Python filename in bot/other_bots/ (e.g. worker_rush.py)', max_length=255)),
                ('bot_class_name', models.CharField(help_text='Class name that inherits from BotAI (e.g. WorkerRushBot)', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'custom_bot',
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_build',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('Macro', 'Macro'), ('Power', 'Power'), ('Rush', 'Rush'), ('Timing', 'Timing'), ('RandomBuild', 'Randombuild')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('MediumHard', 'Mediumhard'), ('Hard', 'Hard'), ('Harder', 'Harder'), ('VeryHard', 'Veryhard'), ('CheatVision', 'Cheatvision'), ('CheatMoney', 'Cheatmoney'), ('CheatInsane', 'Cheatinsane')], default='', max_length=11),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_bot',
            field=models.ForeignKey(blank=True, help_text='Set when the opponent is a custom bot instead of a built-in Computer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_lab.custombot'),
        ),
    ]
