# Generated by Django 6.0.1 on 2026-03-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0007_custombot_alter_match_opponent_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='replay_file',
            field=models.CharField(blank=True, default='', help_text='Path to uploaded replay file for continue-from-replay matches', max_length=500),
        ),
        migrations.AddField(
            model_name='match',
            name='replay_takeover_game_loop',
            field=models.IntegerField(blank=True, help_text='Game loop at which bots take over from the replay', null=True),
        ),
    ]
