# Generated by Django 6.0.1 on 2026-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0008_match_replay_file_match_replay_takeover_game_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='bot_directory',
            field=models.CharField(blank=True, default='', help_text="Directory name under other_bots/ for external bots (e.g. 'who')", max_length=500),
        ),
        migrations.AddField(
            model_name='custombot',
            name='is_external',
            field=models.BooleanField(default=False, help_text='True for third-party bots with their own framework (e.g. ares-sc2 bots)'),
        ),
    ]
