# Generated by Django 6.0.1 on 2026-03-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0009_custombot_bot_directory_custombot_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='aiarena_bot_type',
            field=models.CharField(blank=True, default='python', help_text='Bot type for aiarena matches file: python, cppwin32, cpplinux, dotnetcore, java, nodejs, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='custombot',
            name='bot_type',
            field=models.CharField(choices=[('python_sc2', 'Python Sc2'), ('external_python', 'External Python'), ('aiarena', 'Aiarena')], default='python_sc2', help_text='python_sc2: single .py file in bot/other_bots/; external_python: third-party Python bot with own framework; aiarena: ladder-packaged bot (any language) run via aiarena infrastructure', max_length=20),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_class_name',
            field=models.CharField(blank=True, default='', help_text='Class name that inherits from BotAI (python_sc2 / external_python only)', max_length=100),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_directory',
            field=models.CharField(blank=True, default='', help_text='Directory name under other_bots/ (external_python) or under aiarena/bots/ (aiarena type)', max_length=500),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_file',
            field=models.CharField(blank=True, default='', help_text='Python filename in bot/other_bots/ (python_sc2) or module path (external_python)', max_length=255),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Deprecated: use bot_type instead. Kept for backward compatibility.'),
        ),
    ]
