# Generated by Django 6.0.1 on 2026-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0010_add_aiarena_bot_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_commit_hash',
            field=models.CharField(blank=True, default='', help_text='Git commit hash of the bot version used as opponent (past-version matches)', max_length=40),
        ),
    ]
