# Generated by Django 6.0.1 on 2026-03-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0011_match_opponent_commit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='dockerfile',
            field=models.CharField(blank=True, default='', help_text='Custom Dockerfile name in aiarena/ for mirror/past-version matches (e.g. Dockerfile.bottato)', max_length=100),
        ),
        migrations.AddField(
            model_name='custombot',
            name='git_repo_path',
            field=models.CharField(blank=True, default='', help_text="Absolute path to the bot's git repository (for past version support)", max_length=500),
        ),
        migrations.AddField(
            model_name='custombot',
            name='is_test_subject',
            field=models.BooleanField(default=False, help_text='Whether this bot can be used as Player 1 (the bot being tested/developed)'),
        ),
        migrations.AddField(
            model_name='custombot',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text="Absolute path to the bot's live source directory on the host", max_length=500),
        ),
        migrations.AddField(
            model_name='custombot',
            name='symlink_mounts',
            field=models.JSONField(blank=True, default=list, help_text='Detected symlinks needing separate Docker mounts: [{"name": "...", "target": "..."}]'),
        ),
        migrations.AddField(
            model_name='match',
            name='test_bot',
            field=models.ForeignKey(blank=True, help_text='The bot being tested (Player 1). NULL = BotTato (legacy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_matches', to='test_lab.custombot'),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_class_name',
            field=models.CharField(blank=True, default='', help_text='Deprecated: kept for backward compatibility with older bot registrations.', max_length=100),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_file',
            field=models.CharField(blank=True, default='', help_text='Deprecated: kept for backward compatibility with older bot registrations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_type',
            field=models.CharField(default='aiarena', help_text="Bot type — currently only 'aiarena' is supported.", max_length=20),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Deprecated: kept for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_bot',
            field=models.ForeignKey(blank=True, help_text='Set when the opponent is a custom bot instead of a built-in Computer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_matches', to='test_lab.custombot'),
        ),
    ]
