# Generated by Django 6.0.1 on 2026-03-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0013_backfill_test_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('include_blizzard_ai', models.BooleanField(default=True, help_text='Include the 15 built-in AI matches (3 races x 5 builds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_bots', models.ManyToManyField(blank=True, help_text='Custom bots to include in this test suite', related_name='test_suites', to='test_lab.custombot')),
            ],
            options={
                'db_table': 'test_suite',
            },
        ),
        migrations.AddField(
            model_name='testgroup',
            name='test_suite',
            field=models.ForeignKey(blank=True, help_text='The test suite configuration used for this test group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_groups', to='test_lab.testsuite'),
        ),
    ]
