# Generated by Django 6.0.1 on 2026-03-18 21:06

from django.db import migrations


def create_default_test_suite(apps, schema_editor):
    """Create the default 'All' test suite with Blizzard AI enabled and all custom bots."""
    TestSuite = apps.get_model('test_lab', 'TestSuite')
    CustomBot = apps.get_model('test_lab', 'CustomBot')

    suite, _ = TestSuite.objects.get_or_create(
        name='All',
        defaults={'include_blizzard_ai': True},
    )
    # Add all existing custom bots to the default suite
    suite.custom_bots.set(CustomBot.objects.all())

    # Assign the default suite to all existing test groups that have no suite
    TestGroup = apps.get_model('test_lab', 'TestGroup')
    TestGroup.objects.filter(test_suite__isnull=True).update(test_suite=suite)


def reverse_default_test_suite(apps, schema_editor):
    """Remove the default 'All' test suite."""
    TestSuite = apps.get_model('test_lab', 'TestSuite')
    TestSuite.objects.filter(name='All').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0014_testsuite_testgroup_test_suite'),
    ]

    operations = [
        migrations.RunPython(create_default_test_suite, reverse_default_test_suite),
    ]
