# Generated by Django 6.0.1 on 2026-03-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0015_create_default_all_test_suite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('replay_file', models.CharField(help_text='Path to the .SC2Replay file on the host', max_length=500)),
                ('start_time', models.CharField(help_text="Game clock time to start from, e.g. '2:41'", max_length=20)),
                ('duration', models.CharField(help_text="How long to run before the bot forfeits, e.g. '3:00'", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'replay_test',
            },
        ),
        migrations.AddField(
            model_name='testsuite',
            name='previous_versions',
            field=models.CharField(blank=True, default='', help_text="Comma-separated version offsets for past-version matches. E.g. '1,3' runs against the 1st and 3rd most recent previous commits.", max_length=100),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='replay_tests',
            field=models.ManyToManyField(blank=True, help_text='Replay tests to include in this test suite', related_name='test_suites', to='test_lab.replaytest'),
        ),
    ]
