# Generated by Django 6.0.1 on 2026-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0016_replaytest_testsuite_previous_versions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='enable_version_history',
            field=models.BooleanField(default=False, help_text='Enable past-version matches for this bot (requires git_repo_path)'),
        ),
    ]
