# Generated by Django 6.0.1 on 2026-03-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0017_add_enable_version_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='replay_test',
            field=models.ForeignKey(blank=True, help_text='The replay test that generated this match (auto-set by test suite runner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='test_lab.replaytest'),
        ),
    ]
