# Generated by Django 6.0.1 on 2026-03-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0018_add_replay_test_fk_to_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaytest',
            name='bot_player_id',
            field=models.IntegerField(default=1, help_text='Which player in the replay the test bot takes over (1 or 2)'),
        ),
        migrations.AddField(
            model_name='replaytest',
            name='opponent_bot',
            field=models.ForeignKey(blank=True, help_text='Custom bot to use as the opponent (when opponent_type is CustomBot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_tests', to='test_lab.custombot'),
        ),
        migrations.AddField(
            model_name='replaytest',
            name='opponent_build',
            field=models.CharField(choices=[('Air', 'Air'), ('Macro', 'Macro'), ('Power', 'Power'), ('Rush', 'Rush'), ('Timing', 'Timing'), ('RandomBuild', 'Randombuild')], default='Macro', help_text='Opponent build for built-in AI matches', max_length=15),
        ),
        migrations.AddField(
            model_name='replaytest',
            name='opponent_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('MediumHard', 'Mediumhard'), ('Hard', 'Hard'), ('Harder', 'Harder'), ('VeryHard', 'Veryhard'), ('CheatVision', 'Cheatvision'), ('CheatMoney', 'Cheatmoney'), ('CheatInsane', 'Cheatinsane')], default='CheatInsane', help_text='Opponent difficulty for built-in AI matches', max_length=11),
        ),
        migrations.AddField(
            model_name='replaytest',
            name='opponent_race',
            field=models.CharField(choices=[('Protoss', 'Protoss'), ('Terran', 'Terran'), ('Zerg', 'Zerg'), ('Random', 'Random')], default='Random', help_text='Opponent race for built-in AI matches', max_length=7),
        ),
        migrations.AddField(
            model_name='replaytest',
            name='opponent_type',
            field=models.CharField(choices=[('BuiltInAI', 'Builtinai'), ('CustomBot', 'Custombot')], default='BuiltInAI', help_text='Whether the opponent is a built-in AI or a custom bot', max_length=12),
        ),
    ]
