# Generated by Django 6.0.1 on 2026-03-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0019_replaytest_bot_player_id_replaytest_opponent_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='default_test_suite',
            field=models.ForeignKey(blank=True, help_text='Default test suite used when triggering tests for this bot without specifying a suite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_bots', to='test_lab.testsuite'),
        ),
    ]
