# Generated by Django 6.0.1 on 2026-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0023_remove_custombot_git_repo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive bots are excluded from all test suite runs'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='include_all_custom_bots',
            field=models.BooleanField(default=False, help_text='Include all active custom bots instead of a specific selection'),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='dockerfile',
            field=models.CharField(blank=True, default='', help_text='Custom Dockerfile (relative to test_lab/aiarena/) that builds an image with extra dependencies pre-installed, e.g. Dockerfile.bottato. Saves time when running this bot repeatedly by avoiding per-match installs.', max_length=100),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='enable_version_history',
            field=models.BooleanField(default=False, help_text='Enable past-version matches for this bot (requires source_path to point to a git repo)'),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text="Absolute path to the bot's live development source directory on the host, which may differ from the packaged version in the bots folder", max_length=500),
        ),
    ]
