# Generated by Django 6.0.1 on 2026-03-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0024_custombot_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Protected suites cannot be edited or deleted from the UI'),
        ),
    ]
