# Generated by Django 6.0.1 on 2026-03-21 22:01

from django.db import migrations


def rename_all_to_blizzard_ai(apps, schema_editor):
    """Rename the default 'All' test suite to 'Blizzard AI' and mark it protected."""
    TestSuite = apps.get_model('test_lab', 'TestSuite')
    suite = TestSuite.objects.filter(name='All').first()
    if suite:
        suite.name = 'Blizzard AI'
        suite.is_protected = True
        suite.include_all_custom_bots = False
        suite.save()
    else:
        # If 'All' was already renamed, ensure 'Blizzard AI' exists and is protected
        suite, created = TestSuite.objects.get_or_create(
            name='Blizzard AI',
            defaults={'include_blizzard_ai': True, 'is_protected': True},
        )
        if not created:
            suite.is_protected = True
            suite.save()


def reverse_rename(apps, schema_editor):
    """Revert 'Blizzard AI' back to 'All'."""
    TestSuite = apps.get_model('test_lab', 'TestSuite')
    suite = TestSuite.objects.filter(name='Blizzard AI').first()
    if suite:
        suite.name = 'All'
        suite.is_protected = False
        suite.save()


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0025_add_testsuite_is_protected'),
    ]

    operations = [
        migrations.RunPython(rename_all_to_blizzard_ai, reverse_rename),
    ]
