# Generated by Django 6.0.1 on 2026-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0031_prompttemplate_file_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='logs_dir',
            field=models.CharField(blank=True, default='', help_text='Directory for legacy Docker match logs and replays.', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='replays_dir',
            field=models.CharField(blank=True, default='', help_text='Host path for legacy Docker replays directory.', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sc2_maps_path',
            field=models.CharField(blank=True, default='C:\\Program Files (x86)\\StarCraft II\\Maps', help_text='Host path to StarCraft II Maps directory (mounted into Docker containers).', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sc2_switcher_path',
            field=models.CharField(blank=True, default='C:\\Program Files (x86)\\StarCraft II\\Support\\SC2Switcher.exe', help_text='Path to SC2Switcher.exe for opening replays.', max_length=500),
        ),
    ]
