# Generated by Django 6.0.1 on 2026-03-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0034_custombot_bot_module_bot_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombot',
            name='archive_paths',
            field=models.JSONField(blank=True, default=list, help_text="Paths to extract from git history when testing against past versions. E.g. ['src/', 'bot.py', 'config/']. If empty, the entire tree is archived."),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='dockerfile',
            field=models.CharField(blank=True, default='', help_text='Custom Dockerfile (relative to test_lab/aiarena/) that builds an image with extra dependencies pre-installed, e.g. Dockerfile.mybot. Saves time when running this bot repeatedly by avoiding per-match installs.', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='test_bot',
            field=models.ForeignKey(blank=True, help_text='The bot being tested (Player 1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_matches', to='test_lab.custombot'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='filename',
            field=models.CharField(help_text='Filename (relative to test_lab/prompt_templates/) e.g. mybot.md', max_length=200, unique=True),
        ),
    ]
