# Generated by Django 6.0.1 on 2026-03-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0036_create_adhoc_test_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='logs_dir',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='replays_dir',
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_class',
            field=models.CharField(blank=True, default='', help_text="Python class name that inherits from BotAI (e.g. 'BotTato'). Used by the single-container Docker runner.", max_length=100),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_module',
            field=models.CharField(blank=True, default='', help_text="Python module path for dynamic import (e.g. 'bottato.bottato'). Used by the single-container Docker runner.", max_length=255),
        ),
    ]
