# Generated by Django 6.0.1 on 2026-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0037_remove_logs_dir_replays_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfig',
            old_name='max_concurrent_matches',
            new_name='max_concurrent_custom_bots',
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='max_concurrent_custom_bots',
            field=models.IntegerField(default=0, help_text='Maximum number of custom bot instances that can run at the same time. vs Blizzard AI and replay tests count as 1; vs custom bot and vs past version count as 2. 0 = unlimited.'),
        ),
    ]
