# Generated by Django 6.0.1 on 2026-03-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0038_rename_max_concurrent_to_custom_bots'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bot_actual_race',
            field=models.CharField(blank=True, default='', help_text='Resolved race when bot was set to Random (Protoss/Terran/Zerg)', max_length=7),
        ),
    ]
