# Generated by Django 6.0.1 on 2026-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0041_friendly_race_opponent_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='map_name',
            field=models.CharField(blank=True, default='', help_text='Force all matches in this suite to use a specific map. Empty = auto-select.', max_length=100),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_directory',
            field=models.CharField(blank=True, default='', help_text='Directory name under aiarena/bots/', max_length=500),
        ),
        migrations.AlterField(
            model_name='custombot',
            name='bot_file',
            field=models.CharField(blank=True, default='', help_text="Entry point filename (e.g. 'run.py', 'RustyNikolaj'). Passed as BOT_ENTRY to the Docker runner.", max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='friendly_race',
            field=models.CharField(blank=True, default='', help_text='Race selected for this match. Set pre-match for Random-race bots, or resolved post-match from log.', max_length=7),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='custom_bot_builds',
            field=models.JSONField(blank=True, default=dict, help_text='Per-bot build config overrides: {"<bot_id>": ["build1", ...]}. When a bot ID is present, one match per listed build is launched during test suite runs.'),
        ),
    ]
