# Generated by Django 6.0.1 on 2026-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0042_testsuite_map_name_alter_custombot_bot_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaytest',
            name='state_db_file',
            field=models.CharField(blank=True, default='', help_text='Path to a state snapshot SQLite DB file on the host. Mounted into the container so the bot can restore mid-game state.', max_length=500),
        ),
    ]
