# Generated by Django 6.0.1 on 2026-04-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab', '0043_add_state_db_file_to_replay_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombot',
            name='bot_class',
        ),
        migrations.RemoveField(
            model_name='custombot',
            name='bot_class_name',
        ),
        migrations.RemoveField(
            model_name='custombot',
            name='bot_module',
        ),
    ]
